### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by HappyTetrahedron** [comodal/pagerduty-client#1]
First off, thank you for providing this library, it is a pleasure to use! However, unfortunately my project requires me to use Java 11 (current LTS), which your library is currently not compatible with.

Would you be willing to support target compatibility with Java 11? From a quick look at the source code, it didn't look like the library heavily relies on newer bytecode features, so I was hoping you might relax your target compatibility version a little to support Java 11.

Thank you, and kind regards

**Comment by jpe42** [comment]
Thank you very much for the kind words.  I set the expectation of staying on the latest GA JDK because I want to keep the door open to be able to use the latest features as they come out.  Less so with this library than with its dependency [json-iterator](https://github.com/comodal/json-iterator), e.g. [JEP 338: Vector API](https://openjdk.java.net/jeps/338).  Unfortunately, I don't have the time to maintain multiple releases, but happy to coordinate if someone wants to maintain a JDK 11 or LTS fork.
